### ISSUE TITLE
New Opscenter cluster during re-play

### ISSUE THREAD

**Issue by tagiven** [rackerlabs/ansible-dse#8]
During replays of the opscenter role, the playbook attempts to re-add the cluster into opscenter.  This leads to many failed clusters as dse agents can only be active for a single opscenter cluster at a time.

Instead it should test first if the cluster has been previously added before attempting to add the cluster.

**Comment by seraphin** [comment]
There should be an switch for delete/recreate cluster reference or ignore create cluster reference if exists.

Durring testing you may want to delete and redeploy repeatedly. 
This documents the API call to delete a cluster reference from opscenter
https://docs.datastax.com/en/opscenter/5.0/api/docs/opscenter_config.html

Otherwise the path to ignore the create cluster reference in opscenter and continue of already exists.

**Comment by alexandruanghel** [comment]
The best way would be to ignore adding a cluster if a configuration already exists, but not only that, also to modify the existing configuration, if the configuration changes (for example when adding a new node).

There's not need to delete/recreate a cluster when a new node is added, but just push the new config.
I believe the following commits fixes this so I'll close this issue:
https://github.com/alexandruanghel/ansible-dse/commit/32fea6727e890a0ec7a05949de1f9ead5f829343
https://github.com/alexandruanghel/ansible-dse/commit/89313d4da9807dbd66d14785a9cbd0b792817cc6
